# Generated by Django 2.1.3 on 2019-02-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
