# Generated by Django 2.1.3 on 2019-02-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_usergroup_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='uptime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
