# Generated by Django 2.1.3 on 2019-02-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_usergroup_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type_id',
            field=models.IntegerField(choices=[(1, '超级用户'), (2, '普通用户'), (3, '普普通通用户')], default=1),
        ),
    ]
